apiVersion: v1
kind: Service
metadata:
  name: mediawiki-service
  labels:
    app: mediawiki
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: mediawiki
  type: LoadBalancer
