- hosts: mediawiki_servers
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
      become: yes

    - name: Deploy MediaWiki Configuration File
      template:
        src: templates/LocalSettings.php.j2
        dest: /var/www/html/LocalSettings.php
      become: yes
